TYPE=VIEW
query=select `pst`.`OBJECT_SCHEMA` AS `table_schema`,`pst`.`OBJECT_NAME` AS `table_name`,sum(`pst`.`COUNT_FETCH`) AS `rows_fetched`,sum(`pst`.`SUM_TIMER_FETCH`) AS `fetch_latency`,sum(`pst`.`COUNT_INSERT`) AS `rows_inserted`,sum(`pst`.`SUM_TIMER_INSERT`) AS `insert_latency`,sum(`pst`.`COUNT_UPDATE`) AS `rows_updated`,sum(`pst`.`SUM_TIMER_UPDATE`) AS `update_latency`,sum(`pst`.`COUNT_DELETE`) AS `rows_deleted`,sum(`pst`.`SUM_TIMER_DELETE`) AS `delete_latency`,sum(`fsbi`.`COUNT_READ`) AS `io_read_requests`,sum(`fsbi`.`SUM_NUMBER_OF_BYTES_READ`) AS `io_read`,sum(`fsbi`.`SUM_TIMER_READ`) AS `io_read_latency`,sum(`fsbi`.`COUNT_WRITE`) AS `io_write_requests`,sum(`fsbi`.`SUM_NUMBER_OF_BYTES_WRITE`) AS `io_write`,sum(`fsbi`.`SUM_TIMER_WRITE`) AS `io_write_latency`,sum(`fsbi`.`COUNT_MISC`) AS `io_misc_requests`,sum(`fsbi`.`SUM_TIMER_MISC`) AS `io_misc_latency`,sum(`ibp`.`allocated`) AS `innodb_buffer_allocated`,sum(`ibp`.`data`) AS `innodb_buffer_data`,sum(`ibp`.`pages`) AS `innodb_buffer_pages`,sum(`ibp`.`pages_hashed`) AS `innodb_buffer_pages_hashed`,sum(`ibp`.`pages_old`) AS `innodb_buffer_pages_old`,sum(`ibp`.`rows_cached`) AS `innodb_buffer_rows_cached` from ((`performance_schema`.`table_io_waits_summary_by_table` `pst` left join `performance_schema`.`file_summary_by_instance` `fsbi` on(((`pst`.`OBJECT_SCHEMA` = `extract_schema_from_file_name`(`fsbi`.`FILE_NAME`)) and (`pst`.`OBJECT_NAME` = `extract_table_from_file_name`(`fsbi`.`FILE_NAME`))))) left join `sys`.`x$innodb_buffer_stats_by_table` `ibp` on(((`pst`.`OBJECT_SCHEMA` = `ibp`.`object_schema`) and (`pst`.`OBJECT_NAME` = `ibp`.`object_name`)))) group by `pst`.`OBJECT_SCHEMA`,`pst`.`OBJECT_NAME` order by sum(`pst`.`SUM_TIMER_WAIT`) desc
md5=b5062130905537854839b41b7c26dca2
updatable=0
algorithm=1
definer_user=root
definer_host=localhost
suid=0
with_check_option=0
timestamp=2014-06-22 00:20:00
create-version=1
source=SELECT pst.object_schema AS table_schema,\n       pst.object_name AS table_name,\n       SUM(pst.count_fetch) AS rows_fetched,\n       SUM(pst.sum_timer_fetch) AS fetch_latency,\n       SUM(pst.count_insert) AS rows_inserted,\n       SUM(pst.sum_timer_insert) AS insert_latency,\n       SUM(pst.count_update) AS rows_updated,\n       SUM(pst.sum_timer_update) AS update_latency,\n       SUM(pst.count_delete) AS rows_deleted,\n       SUM(pst.sum_timer_delete) AS delete_latency,\n       SUM(fsbi.count_read) AS io_read_requests,\n       SUM(fsbi.sum_number_of_bytes_read) AS io_read,\n       SUM(fsbi.sum_timer_read) AS io_read_latency,\n       SUM(fsbi.count_write) AS io_write_requests,\n       SUM(fsbi.sum_number_of_bytes_write) AS io_write,\n       SUM(fsbi.sum_timer_write) AS io_write_latency,\n       SUM(fsbi.count_misc) AS io_misc_requests,\n       SUM(fsbi.sum_timer_misc) AS io_misc_latency,\n       SUM(ibp.allocated) AS innodb_buffer_allocated,\n       SUM(ibp.data) AS innodb_buffer_data,\n       SUM(ibp.pages) AS innodb_buffer_pages,\n       SUM(ibp.pages_hashed) AS innodb_buffer_pages_hashed,\n       SUM(ibp.pages_old) AS innodb_buffer_pages_old,\n       SUM(ibp.rows_cached) AS innodb_buffer_rows_cached\n  FROM performance_schema.table_io_waits_summary_by_table AS pst\n  LEFT JOIN performance_schema.file_summary_by_instance AS fsbi\n    ON pst.object_schema = extract_schema_from_file_name(fsbi.file_name)\n   AND pst.object_name = extract_table_from_file_name(fsbi.file_name)\n  LEFT JOIN sys.x$innodb_buffer_stats_by_table AS ibp\n    ON pst.object_schema = ibp.object_schema\n   AND pst.object_name = ibp.object_name\n GROUP BY pst.object_schema, pst.object_name\n ORDER BY SUM(pst.sum_timer_wait) DESC
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `pst`.`OBJECT_SCHEMA` AS `table_schema`,`pst`.`OBJECT_NAME` AS `table_name`,sum(`pst`.`COUNT_FETCH`) AS `rows_fetched`,sum(`pst`.`SUM_TIMER_FETCH`) AS `fetch_latency`,sum(`pst`.`COUNT_INSERT`) AS `rows_inserted`,sum(`pst`.`SUM_TIMER_INSERT`) AS `insert_latency`,sum(`pst`.`COUNT_UPDATE`) AS `rows_updated`,sum(`pst`.`SUM_TIMER_UPDATE`) AS `update_latency`,sum(`pst`.`COUNT_DELETE`) AS `rows_deleted`,sum(`pst`.`SUM_TIMER_DELETE`) AS `delete_latency`,sum(`fsbi`.`COUNT_READ`) AS `io_read_requests`,sum(`fsbi`.`SUM_NUMBER_OF_BYTES_READ`) AS `io_read`,sum(`fsbi`.`SUM_TIMER_READ`) AS `io_read_latency`,sum(`fsbi`.`COUNT_WRITE`) AS `io_write_requests`,sum(`fsbi`.`SUM_NUMBER_OF_BYTES_WRITE`) AS `io_write`,sum(`fsbi`.`SUM_TIMER_WRITE`) AS `io_write_latency`,sum(`fsbi`.`COUNT_MISC`) AS `io_misc_requests`,sum(`fsbi`.`SUM_TIMER_MISC`) AS `io_misc_latency`,sum(`ibp`.`allocated`) AS `innodb_buffer_allocated`,sum(`ibp`.`data`) AS `innodb_buffer_data`,sum(`ibp`.`pages`) AS `innodb_buffer_pages`,sum(`ibp`.`pages_hashed`) AS `innodb_buffer_pages_hashed`,sum(`ibp`.`pages_old`) AS `innodb_buffer_pages_old`,sum(`ibp`.`rows_cached`) AS `innodb_buffer_rows_cached` from ((`performance_schema`.`table_io_waits_summary_by_table` `pst` left join `performance_schema`.`file_summary_by_instance` `fsbi` on(((`pst`.`OBJECT_SCHEMA` = `extract_schema_from_file_name`(`fsbi`.`FILE_NAME`)) and (`pst`.`OBJECT_NAME` = `extract_table_from_file_name`(`fsbi`.`FILE_NAME`))))) left join `sys`.`x$innodb_buffer_stats_by_table` `ibp` on(((`pst`.`OBJECT_SCHEMA` = `ibp`.`object_schema`) and (`pst`.`OBJECT_NAME` = `ibp`.`object_name`)))) group by `pst`.`OBJECT_SCHEMA`,`pst`.`OBJECT_NAME` order by sum(`pst`.`SUM_TIMER_WAIT`) desc
